### ISSUE TITLE
hello~i want contribute this repository

### ISSUE THREAD

**Issue by Lee-Seong-Ju** [vichitr/HacktoberfestForBeginners#113]
hello.
sorry i begin github 7days ago,,,so im very beginner,,,
i want insert Dijkstra Algorithm so i make new branch and add->commit->push . but occur problem "unable to access~~The requested URL returned error : 403" ㅠㅠㅠㅠㅠ how to solved this problem....

**Comment by vichitr** [comment]
Just go to algorithms folder and then click on upload files(upload from your PC) or add files(paste the code). and then click on commit new file. This should work fine.

**Comment by Lee-Seong-Ju** [comment]
![캡처](https://user-images.githubusercontent.com/55746374/66752980-b42c0180-eecd-11e9-9ca0-4a4eb98136b7.PNG)
ㅠㅠㅠi proceed upload file -> Algorithm folder,,,,but this problem occur,,,

**Comment by vichitr** [comment]
No you can't push. That's why i'm asking to do it using it's website.

**Comment by vichitr** [comment]
search how to send pull request with commands. You can't commit to the repo directly. Instead create pull request.

**Comment by Pankajtanwarbanna** [comment]
@Lee-Seong-Ju You need to fork the repo first in order to gain access.

**Comment by Lee-Seong-Ju** [comment]
@Pankajtanwarbanna @vichitr ㅠㅠㅠ So so thank you friends,,,,,i github beginner so very difficult now,,,,sorry sorry
